# Estimate calibration curve {#calibration}
## The four-parameter logistic curve
The relationship between concentration and absorbance can be described by the so called _four-parameter logistic equation (4-PL)_. We will use the following equation:

$$f(c) =  \mathrm{A_{min}} + \frac{\mathrm{A_{max}} - \mathrm{A_{min}}}{1+\exp(\mathrm{n} \cdot (\log_2(c)-\log_2(\mathrm{EC}_{50})))}$$,

where $\mathrm{A}$ stands for absorbance and $c$ for concentration. The parameters that we are going to estimate are $\mathrm{A_{max}}$, which is the maximal absorbance that can be obtained (for infinite concentration $c \rightarrow \infty$), $\mathrm{A_{min}}$, which is the minimum absorbance that can be obtained (for $c \rightarrow 0$), and parameters $\mathrm{EC}_{50}$ and $n$. The value of $\log \mathrm{EC}_{50}$ is the inflection point of the curve. This means, $\log \mathrm{EC}_{50}$ is the concentration for which we obtain 50% of $\mathrm{A_{max}}$. Parameter $n$ is related to the steepness of the curve at the inflection point. 

For convenience, we use $\log_2$ in the equation (and not $log_{10}$ as often used in literature), because then the estimated $\log_2 EC_{50}$ is easier to interpret, since we performed a 1:2 dilution series to generate the concentrations of our standard. Note that $\log_2(x) = \frac{log_{10}(x)}{log_2(10)} = 0.30103 \cdot \log_{10}(x)$. Changing the base simply scales all concentration by a constant value (linear transformation).

## Regression of the standard
We fit the data obtained for the standard to the four-parameter logistic curve:
```{r, regress-std, echo = TRUE, eval = F, warning = FALSE, message = FALSE}
# Fit 4-parameter logistic dose-response curve using the drc package
# NOTE: the drm function performs a log10(x) transformation by itself.
# See also ?LL2.4 for more information
drc.fit <- drm(absorbance ~ dilution, 
               data = standard, 
               fct = LL2.4(names=c("n", "Amin", "Amax", "EC50")))
drc.fit <- drm(absorbance ~ dilution, data = standard, fct = LL2.4(fixed = c(NA, median(blanks$blank), NA, NA), names=c("n", "Amin", "Amax", "EC50")))
summary(drc.fit)
plot(drc.fit)
# Check residuals
qplot(as.tibble(drc.fit$predres)$`Predicted values`, as.tibble(drc.fit$predres)$Residuals)

# Compare to nls fit
nls.fit <- nls(absorbance ~ 0.003 + ((Amax - 0.003)/(1 + exp(n * (log2(dilution) - log2EC50)))), 
                data = standard,
                start = list(Amax = 2, log2EC50 = 9, n = -1))
 summary(nls.fit)
 plot(nls.fit)

# Compare to Levenber-Marquardt fit
levm.fit = nlsLM(absorbance ~ 0.003 + ((Amax - 0.003)/(1 + exp(n * (log2(dilution) - log2EC50)))), data = standard,start = list(Amax = 2, log2EC50 = 9, n = -1))
lefm.sum <- summary(levm.fit)
predict(levm.fit)

plot(levm.fit)

# TODO:
#make table with estimates
#plot predictions in one plot
```

## Summary 