# Results {#results}
## Compute concentrations
Rearranging the 4-PL equation for concentration $c$ gives:

$$\log_2(c) = \log_2(\mathrm{EC}_{50}) + \dfrac{1}{n} \cdot \ln \left(\dfrac{\mathrm{A_{max} - A_{min}}}{A - \mathrm{A_{min}}} \right) $$.

We compute the concentrations of our biological samples using the estimated calibration curve and plot the results:
```{r, results, echo = TRUE, eval = TRUE, warning = FALSE, message = FALSE, cache = TRUE}

log2concentration.est <- sapply(donors.av$absorbance.av,
  function(x)
  log2EC50.est + (1/n.est) * log((Amax.est - Amin)/(x - Amin)))


# Get confidence intervals
fgh <- deriv(
  log2concentration ~ log2EC50 + (1/n) * log((Amax - Amin)/(A - Amin)),
  c("Amax", "log2EC50", "n"), function(Amax, log2EC50, n, A) {}
)
f.new <- fgh(Amax.est, log2EC50.est, n.est, donors.av$absorbance.av)
g.new <- attr(f.new, "gradient")
gs <- rowSums((g.new %*% cov.fit) * g.new)
alpha <- 0.05
delta.f <- sqrt(gs) * qt(1 - alpha/2, 15)
results <- donors.av %>% 
  dplyr::mutate(concentration.est = 2^log2concentration.est) %>%
  dplyr::mutate(log2concentration.est = log2concentration.est) %>%
  dplyr::mutate(log2conf = delta.f) 

# Inspect results
head(results)
```

## Plot results
```{r, plot-results, echo = TRUE, eval = TRUE, warning = FALSE, message = FALSE, fig.height=4, cache = TRUE}
plot.results <- ggplot(
    data = results,
    aes(time, concentration.est, color = donor)
  ) +
  geom_line(aes(time, concentration.est, group = donor), 
    alpha = 0.6, lwd = 0.5
  ) +
  labs(
    x = "Days after vaccination",
    y = "Relative concentration",
    title = "IgG in healthy volunteers"
  ) +
  scale_color_viridis(
    begin = 0.2, end = 0.8, discrete = TRUE,
    labels = paste("Donor", seq(n.donors)), guide = guide_legend(title = "")
  ) +
  scale_x_continuous(breaks = tpoints) +
  background_grid(
    major = "yx", minor = "", colour.major = "grey90", size.major = 0.2
  ) +
  theme_plot() +
  geom_pointrange(
    aes(ymin = concentration.est / 2^log2conf, 
        ymax = concentration.est * 2^log2conf), 
    shape = 21, size = 0.4
  ) +
  scale_y_continuous(labels = scales::percent)

plot.results
```